// <auto-generated />
using System;
using DevelopsTodayTask.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevelopsTodayTask.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20250124130048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("DevelopsTodayTask.Models.TripData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DOLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FareAmount")
                        .HasColumnType("REAL");

                    b.Property<int>("PULocationID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TipAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TpepDropoffDatetime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TpepPickupDatetime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TripDistance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DOLocationID")
                        .HasDatabaseName("idx_dolocation_id");

                    b.HasIndex("PULocationID")
                        .HasDatabaseName("idx_pulocation_id");

                    b.HasIndex("TipAmount")
                        .HasDatabaseName("idx_tip_amount");

                    b.HasIndex("TpepDropoffDatetime")
                        .HasDatabaseName("idx_dropoff_datetime");

                    b.HasIndex("TpepPickupDatetime")
                        .HasDatabaseName("idx_pickup_datetime");

                    b.HasIndex("TripDistance")
                        .HasDatabaseName("idx_trip_distance");

                    b.HasIndex("TpepPickupDatetime", "TpepDropoffDatetime", "PassengerCount")
                        .IsUnique();

                    b.ToTable("Trips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
