// <auto-generated />
using System;
using DevelopsTodayTask.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevelopsTodayTask.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevelopsTodayTask.Models.TripData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<double>("FareAmount")
                        .HasColumnType("float");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TipAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("TpepDropoffDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TpepPickupDatetime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TripDistance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DOLocationID")
                        .HasDatabaseName("idx_dolocation_id");

                    b.HasIndex("PULocationID")
                        .HasDatabaseName("idx_pulocation_id");

                    b.HasIndex("TipAmount")
                        .HasDatabaseName("idx_tip_amount");

                    b.HasIndex("TpepDropoffDatetime")
                        .HasDatabaseName("idx_dropoff_datetime");

                    b.HasIndex("TpepPickupDatetime")
                        .HasDatabaseName("idx_pickup_datetime");

                    b.HasIndex("TripDistance")
                        .HasDatabaseName("idx_trip_distance");

                    b.HasIndex("TpepPickupDatetime", "TpepDropoffDatetime", "PassengerCount")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_trip_times")
                        .HasFilter("[PassengerCount] IS NOT NULL");

                    b.ToTable("Trips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
